# Generated by Django 3.0 on 2020-08-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
