# Generated by Django 3.0 on 2020-08-26 14:07

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
