# Generated by Django 3.0 on 2020-08-26 11:32

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200825_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
